export const LOGIN_ROUTER = '/login'
export const REGISTR_ROUTER = '/'
export const CARDS_ROUTER = '/cards'
export const WALLET_ROUTER = '/wallet'
export const EXPENSES_ROUTER = '/expense'
export const INCOMES_ROUTER = '/incomes'
